---
title: "neolithicHeight_analysis"
output: html_document
date: '2023-02-21'
---

```{r setup, include=FALSE}
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(ggvenn)
library(ggplot2)
library(stringr)
library(reshape2)
library(ggsignif)
library(ggbeeswarm)
library(RColorBrewer)
library(data.table)
library(forcats)

#source("lbkFunctions.R")
## read in the data
compiled <- read.csv("../SupplementaryTable1.csv")

## making sure all the data classes are correct after importing them
compiled$prs_scaled <- as.numeric(compiled$prs_scaled)
compiled$imputed_prs_scaled <- as.numeric(compiled$imputed_prs_scaled)
compiled$sibling_prs_imputed <- as.numeric(compiled$sibling_prs_imputed)
compiled$method <- as.factor(compiled$method)
compiled$Sex <- as.factor(compiled$Sex)
compiled$Sex <- factor(compiled$Sex, levels=c("F", "M", "J", "U"))
compiled$Country <- as.factor((compiled$Country))
compiled$Region <- as.factor(compiled$Region)
compiled$Region <- factor(compiled$Region, levels=c("North Central", "South Central", "balkan", "mediterranean", "HG", "anatoliaEF"))
compiled$CO <- as.factor(compiled$CO)
compiled$LEH <- as.factor(compiled$LEH)
compiled$whgProp <- as.numeric(compiled$whgProp)

## create a dataset without the Mesolithic Hunter-Gatherers and Anatolian Farmers
neoOnly <- compiled[compiled$Region != "HG" & compiled$Region != "anatoliaEF",]

## read in data for supplementary figures
suppData <- read.csv("supplementaryData.csv")
suppData$Region <- factor(suppData$Region, levels=c("North Central", "South Central", "balkan", "mediterranean", "HG", "anatoliaEF"))

## color palettes for plotting
palette2 <- c("#1B9E77", "#82d682", "#D95F02", "#1275A3", "#BB83A1", "#A8DFF1") ## color palette: including HG and EF colors
palette3 <- c("#1B9E77", "#82d682", "#D95F02", "#1275A3", "grey75") ## color palette: no HG or EF colors, modern samples in grey
palette4 <- c("#1B9E77", "#82d682", "#D95F02", "#1275A3", "#BB83A1", "#A8DFF1", "grey75") ## color palette: including HG and EF colors, modern samples in grey
paleoColors <- c("#495B76", "#609FA6") ## color palette: paleopathology presence/absence

```
## Results
```{r Results, echo=FALSE, out.width="50%", warning=FALSE}
females <- subset(neoOnly, Sex=="F")
males <- subset(neoOnly, Sex=="M")

ttest1 <- pairwise.t.test(neoOnly$imputed_prs_scaled, neoOnly$Region)
lm1 <- lm(femur_estimated ~ Sex * Region, data = compiled)
lm2 <- lm(femur_estimated ~ Region, data=males)
lm3 <- lm(femur_estimated ~ Region, data=females)
```


## Fig 2
```{r Fig2, echo=FALSE, out.width="50%", warning=FALSE}

## create the sample maps
europe <- ne_countries(scale = "medium", returnclass = "sf", continent="Europe")
map <- ggplot(data = europe) +
  geom_sf() +
  xlab("Longitude") + ylab("Latitude") +
  geom_point(data=compiled[compiled$dna_ID != "",], aes(x=Longitude, y=Latitude, col=Region)) +
  #scale_color_brewer(palette="Dark2") +
  scale_color_manual(values=palette2) +
   coord_sf(xlim = c(-10, 30), ylim = c(35, 55))+
   theme_light() +
  ggtitle("2A) Map of genetic sites")
print(map)

map2 <- ggplot(data = europe) +
  geom_sf() +
  xlab("Longitude") + ylab("Latitude") +
  geom_point(data=compiled[compiled$metric_ID != "",], aes(x=Longitude, y=Latitude, col=Region)) +
  #scale_color_brewer(palette="Dark2") +
  scale_size_continuous(breaks=c(10, 50, 100)) +
   scale_color_manual(values=palette2) +
  coord_sf(xlim = c(-10, 30), ylim = c(35, 55))+
   theme_light() +
  ggtitle("2B) Map of skeletal sites")
print(map2)

## import the smartPCA data
impPCA <- read.csv("impPCA_neoData.csv")
impPCA$Region <- as.factor(impPCA$Region)
## reorganize factor levels for plotting
impPCA$Region <- factor(impPCA$Region, levels=c("North Central", "South Central", "balkan", 
                                                          "mediterranean", "modern"))
## make the imputed PCA plot
ggplot(data=impPCA, aes(x=PC1, y=-PC2, col=Region, stroke=0)) +
    geom_point() +
    scale_color_manual(values=palette3) +
    labs(x="PC1", y="PC2") +
    ggtitle("2C) Genetic Ancestry: projected PCA (imputed)") +
    theme_light()

## plot of all samples by date in years BP
neoOnly$type <- ifelse(neoOnly$dna_ID != "", "genetic", "skeletal")
ggplot(data=neoOnly, aes(x=Region, y=Date, col=Region)) + 
  geom_beeswarm(dodge.width=0.95) +
  scale_color_manual(values=palette2) +
  facet_wrap(~type) + 
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90)) + 
  ggtitle("2D) Samples by Date (yearsBP)")
```

``` {r sexDim, echo=FALSE, warning=FALSE}
## table of sexual dimorphism ratios in femur length (femDiff)
femDiff <- aggregate(femur_estimated ~ Sex + Region, data=compiled, mean)
femDiffF <- subset(femDiff, Sex=="F")
femDiffM <- subset(femDiff, Sex=="M")
femDiff <- femDiffF[,2:3]
femDiff$MtoF_femur <- NA
femDiff$percentDiff <- NA
for(i in 1:nrow(femDiffF)){
   femDiff[i,4] <- femDiffM[i,3]/femDiffF[i,3]
   femDiff[i,3] <- (femDiffM[i,3] - femDiffF[i,3])/femDiffF[i,3] * 100
}
femDiff <- femDiff[,-2]

print(femDiff)
```


## Fig 3
```{r fig3, echo=FALSE, out.width="50%", warning=FALSE}

ggplot(data=neoOnly, aes(y=imputed_prs_scaled, x=Region, col=Region, shape=Sex, stroke=0)) +
   geom_beeswarm(dodge.width = 0.75) +
   stat_summary( fun = "mean",
               fun.max = function(x) mean(x) + sd(x) / sqrt(length(x)),
               fun.min = function(x) mean(x) - sd(x) / sqrt(length(x)), 
               geom = "errorbar", col = "black", width=.5, position="dodge") +
   stat_summary(fun = "mean", geom = "point", col = "black", size=2, position="dodge") +
   scale_color_manual(values=palette2) +
   theme_light() +
   geom_signif(comparisons=list(c("Northern LBK", "mediterranean")), test=t.test) + 
   ggtitle("3A) PRS of Neolithic Europeans")

ggplot(data=neoOnly, aes(y=femur_estimated, x=Region, col=Region, shape=Sex, fill=Sex, stroke=0)) +
   geom_beeswarm(dodge.width=0.75) +
   stat_summary(fun = "mean",
               fun.max = function(x) mean(x) + sd(x) / sqrt(length(x)),
               fun.min = function(x) mean(x) - sd(x) / sqrt(length(x)), 
               geom = "errorbar", col = "black", width=.5, position="dodge") +
   stat_summary(fun = "mean", geom = "point", col = "black", size=2, position="dodge") +
   scale_color_manual(values=palette2) +
   theme_light() +
   theme(axis.text.x = element_text(angle = 90)) +
   ggtitle("3B) Femur length of Neolithic Europeans")

ggplot(data=neoOnly, aes_string(y="d15N", x="d13C", col="Region", stroke=0)) +
   geom_point() +
   theme(axis.text.x = element_text(angle = 90)) +
   guides(scale="none") +
   scale_color_manual(values=palette2) +
   theme_light() +
   ggtitle("3C: d13C and d15N")

ggplot(data=neoOnly[!(is.na(neoOnly$Sex)),], aes(x=Region, y=d15N, shape=Sex, col=Region, stroke=0)) +
   #geom_boxplot() +
   # guides(size=FALSE) +
   geom_beeswarm(dodge.width=0.75) +
   stat_summary(fun = "mean",
               fun.max = function(x) mean(x) + sd(x) / sqrt(length(x)),
               fun.min = function(x) mean(x) - sd(x) / sqrt(length(x)), 
               geom = "errorbar", col = "black", width=.5, position="dodge") +
   stat_summary(fun = "mean", geom = "point", col = "black", size=2, position="dodge") +
   scale_color_manual(values=palette2) +
   theme_light() +
   ggtitle("3D: sex differences in d15N")

```

## Fig 4
```{r fig4, echo=FALSE, out.width="50%", warning=FALSE}
## subset data for plotting just Central European samples
isoplot <- subset(compiled, Region == "North Central" | Region == "South Central")
## remove individuals which do not have stable isotopic data
isoplot <- subset(isoplot, !(is.na(isoplot$d15N)) | !(is.na(isoplot$d13C)))
## remove factor levels from the full dataset which are not present in this subset
isoplot$Region <- droplevels(isoplot$Region)
isoplot$Sex <- droplevels(isoplot$Sex)
## reshape the data for easier ggplotting
isoplot <- reshape2::melt(isoplot, id.vars=c("isotope_ID", "Sex", "Region"), measure.vars=c("d15N", "d13C"))

ggplot(data=isoplot[isoplot$Sex == "M" | isoplot$Sex == "F",], aes(y=value, x=Region, col=Sex, fill=Sex, stroke=0)) +
   # geom_boxplot() +
   geom_beeswarm(dodge.width=0.75) +
   scale_color_manual(values=palette2) +
   stat_summary(fun = "mean",
               fun.max = function(x) mean(x) + sd(x) / sqrt(length(x)),
               fun.min = function(x) mean(x) - sd(x) / sqrt(length(x)), 
               geom = "errorbar", col = "black", width=.5, position="dodge") +
   stat_summary(fun = "mean", geom = "point", col = "black", size=2, position="dodge") +
   geom_signif(comparisons=list(c("LBK", "mediterranean")), test=t.test) + 
   facet_wrap(~variable, scales="free_y") +
   theme_light() +
   ggtitle("4A) LBK isotopes by sex")


LEHplot <- compiled[!is.na(compiled$LEH),]
LEHplot <- subset(LEHplot, Sex == "M" | Sex == "F")
LEHplot$Region <- droplevels(LEHplot$Region)
LEHplot$Sex <- droplevels(LEHplot$Sex)

ggplot(data=LEHplot, aes(x=Region, fill=LEH, stroke=0)) +
   geom_bar(position="fill") +
   facet_grid(~Sex) +
   scale_y_continuous(labels = scales::percent) +
   scale_fill_manual(values=paleoColors) +
   guides(size=FALSE) +
   theme_light() +
   ggtitle("4B) LBK femur and linear enamel hypoplasia")

ggplot(data=LEHplot[!is.na(LEHplot$Sex) & plotdata$LEH != "",], aes(y=femur_estimated, x=Region, fill=LEH, shape=Sex, stroke=0)) +
   geom_beeswarm(dodge.width=0.75, aes(col=LEH)) +
   stat_summary(fun = "mean",
               fun.max = function(x) mean(x) + sd(x) / sqrt(length(x)),
               fun.min = function(x) mean(x) - sd(x) / sqrt(length(x)),
               geom = "errorbar", col = "black", width=.5, position="dodge") +
   stat_summary(fun = "mean", geom = "point", col = "black", size=2, position="dodge") +
   scale_color_manual(values=paleoColors) +
   theme_light() +
   ggtitle("4C) LBK femur and linear enamel hypoplasia")

```

## Fig 5
```{r fig5, echo=FALSE, out.width="50%", warning=FALSE}
## read in data from smartPCA including WHG and Anatolian Farmers
impPCAall <- read.csv("impPCA_allData.csv")
impPCAall$Region <- as.factor(impPCAall$Region)
## reorder the Region factor levels
impPCAall$Region <- factor(impPCAall$Region, levels=c("North Central", "South Central", "balkan", "mediterranean", "HG", "anatoliaEF", "modern"))

ggplot(data=impPCAall, aes(x=PC1, y=-PC2, col=Region, stroke=0)) +
    geom_point() +
    scale_color_manual(values=palette4) +
    labs(x="PC1", y="PC2") +
    ggtitle("5A) Genetic Ancestry: projected PCA (imputed)") +
    theme_light()



## read in the ADMIXTURE results 
mix <- read.table("admixtureData.txt", header=TRUE)
## reorder factor levels for plotting
mix$Region <- factor(mix$Region, levels=c("North Central", "South Central", "balkan", 
                                                "mediterranean", "HG", "anatoliaEF"))
## order dataframe by admixture proportion for plotting
mix$ID <-fct_reorder(mix$ID, mix$EF)
## make admixture data long form for plotting
toplotMix <- reshape2::melt(mix, c("ID", "Region", "Sex"))
toplotMix$variable <- factor(toplotMix$variable, levels=c("EF", "WHG"))

ggplot(data=toplotMix, aes(x=ID, y=value, fill=variable, col=variable), position="stack") +
  geom_col() +
  facet_grid(~Region, scales="free_x", space="free_x") + 
  scale_fill_manual(values=palette4[5:6]) +
  scale_color_manual(values=palette4[5:6]) +
  theme_classic() +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) +
  ggtitle("5B) ADMIXTURE")

ggplot(data=compiled, aes(y=prs_scaled, x=Region, col=Region, stroke=0)) +
   geom_beeswarm(cex=2) +
   stat_summary( fun = "mean",
               fun.max = function(x) mean(x) + sd(x) / sqrt(length(x)),
               fun.min = function(x) mean(x) - sd(x) / sqrt(length(x)), 
               geom = "errorbar", col = "black", width=.5) +
   stat_summary(fun = "mean", geom = "point", col = "black", size=2) +
   scale_color_manual(values=palette2) +
   theme_light() +
   ggtitle("5C) PRS of Neolithic Europeans, Hunter-Gatherers, and Anatolia Farmers")

ggplot(data=compiled, aes(y=sibling_prs_imputed, x=Region, col=Region, stroke=0)) +
   geom_beeswarm(cex=2) +
   stat_summary( fun = "mean",
               fun.max = function(x) mean(x) + sd(x) / sqrt(length(x)),
               fun.min = function(x) mean(x) - sd(x) / sqrt(length(x)), 
               geom = "errorbar", col = "black", width=.5) +
   stat_summary(fun = "mean", geom = "point", col = "black", size=2) +
   scale_color_manual(values=palette2) +
   theme_light() +
   ggtitle("5D) Sibling-based PRS of Neolithic Europeans, Hunter-Gatherers, and Anatolia Farmers")

```

# Supplemenary Figures
## Supp Fig 1
```{r suppFig1, echo=FALSE, out.width="50%", warning=FALSE}
venn <- list("DNA"=which(compiled$dna_ID != ""), "isotopes"=which(compiled$isotope_ID != ""), "metrics"=which(compiled$metric_ID != ""), "pathology"=which(compiled$paleopath_ID != ""))
ggvenn(venn, fill_color = c("#0073C2FF", "#EFC000FF", "#CD534CFF", "grey"), stroke_size = 0.5, show_percentage = FALSE, text_size = 5) +
  scale_x_continuous(expand = expansion(mult = .2)) +
  ggtitle("Supp.Fig. 1: Data set counts")

```

## Supp Fig 2
```{r suppFig2, echo=FALSE, out.width="50%", warning=FALSE}

lm41 <- lm(asMales_prs ~ Sex + Region, data=suppData)
lm42 <- lm(asFemales_prs ~ Sex + Region, data=suppData)
lm43 <- lm(sexspec_prs ~ Sex + Region, data=suppData)
lm44 <- lm(combo_prs ~ Sex + Region, data=suppData)
# lm44 <- lm(clumpImp ~ Region, data=suppData)
# lm45 <- lm(clumpImp_sibs ~ Region, data=suppData)
# lm46 <- lm(clumpUnImp ~ Sex * Region, data=suppData)
# lm47 <- lm(clumpUnImp_sibs ~ Sex * Region, data=suppData)

ggplot(data=suppData, aes(y=combo_prs, x=Region, col=Region, shape=Sex, stroke=0)) +
   #geom_boxplot() +
   geom_beeswarm(dodge.width=0.75, cex=2) +
   stat_summary(fun = "mean",
               fun.max = function(x) mean(x) + sd(x) / sqrt(length(x)),
               fun.min = function(x) mean(x) - sd(x) / sqrt(length(x)), 
               geom = "errorbar", col = "black", width=.5, position="dodge") +
   stat_summary(fun = "mean", geom = "point", col = "black", size=2, position="dodge") +
   scale_color_manual(values=palette2) +
   theme_light() +
   ggtitle("A) Neale Lab Combined Sex sumstats")

ggplot(data=suppData, aes(y=asMales_prs, x=Region, col=Region, shape=Sex, stroke=0)) +
   geom_beeswarm(dodge.width=0.75, cex=2) +
   stat_summary(fun = "mean",
               fun.max = function(x) mean(x) + sd(x) / sqrt(length(x)),
               fun.min = function(x) mean(x) - sd(x) / sqrt(length(x)), 
               geom = "errorbar", col = "black", width=.5, position="dodge") +
   stat_summary(fun = "mean", geom = "point", col = "black", size=2, position="dodge") +
   scale_color_manual(values=palette2) +
   theme_light() +
   ggtitle("B) Neale Lab Male sumstats")

ggplot(data=suppData, aes(y=asFemales_prs, x=Region, col=Region, shape=Sex, stroke=0)) +
   geom_beeswarm(dodge.width=0.75, cex=2) +
   stat_summary(fun = "mean",
               fun.max = function(x) mean(x) + sd(x) / sqrt(length(x)),
               fun.min = function(x) mean(x) - sd(x) / sqrt(length(x)), 
               geom = "errorbar", col = "black", width=.5, position="dodge") +
   stat_summary(fun = "mean", geom = "point", col = "black", size=2, position="dodge") +
   scale_color_manual(values=palette2) +
   theme_light() +
   ggtitle("C) Neale Lab Female sumstats")

ggplot(data=suppData, aes(y=sexspec_prs, x=Region, col=Region, shape=Sex, stroke=0)) +
   geom_beeswarm(dodge.width=0.75, cex=2) +
   stat_summary(fun = "mean",
               fun.max = function(x) mean(x) + sd(x) / sqrt(length(x)),
               fun.min = function(x) mean(x) - sd(x) / sqrt(length(x)), 
               geom = "errorbar", col = "black", width=.5, position="dodge") +
   stat_summary(fun = "mean", geom = "point", col = "black", size=2, position="dodge") +
   scale_color_manual(values=palette2) +
   theme_light() +
   ggtitle("D) Neale Lab sex-specific sumstats")


```

## Supp Fig 3
```{r suppFig3, echo=FALSE, warning=FALSE}
ggplot(data=suppData, aes(y=siblings_prs_ldpred, x=Region, col=Region, stroke=0)) +
   geom_beeswarm(cex=2) +
   stat_summary( fun = "mean",
               fun.max = function(x) mean(x) + sd(x) / sqrt(length(x)),
               fun.min = function(x) mean(x) - sd(x) / sqrt(length(x)), 
               geom = "errorbar", col = "black", width=.5) +
   stat_summary(fun = "mean", geom = "point", col = "black", size=2) +
   scale_color_manual(values=palette2) +
   theme_light() +
   geom_signif(comparisons=list(c("Northern LBK", "mediterranean")), test=t.test) + 
   ggtitle("A) Sibling LDPred2 PRS")

ggplot(data=compiled, aes(y=imputed_prs_scaled, x=femur_estimated)) +
   geom_point(aes(col=Region)) +
   geom_smooth(method="lm") +
   scale_color_manual(values=palette2) +
   theme_light() +
   ggtitle("B) Sibling PRS vs Femur length")

```
## Supp Fig 4
```{r suppFig4, echo=FALSE, warning=FALSE}
## import data for the unimputed Neolithic PCA
unimpPCA <- read.csv("unimpPCA_neoData.csv")
unimpPCA$Region <- as.factor(unimpPCA$Region)
## reorder the factor levels for plotting
unimpPCA$Region <- factor(unimpPCA$Region, levels=c("North Central", "South Central", "balkan",
                                                          "mediterranean", "modern"))

ggplot(data=unimpPCA, aes(x=-PC1, y=PC2, col=Region, stroke=0)) +
    geom_point() +
    scale_color_manual(values=palette3) +
    labs(x="PC1", y="PC2") +
    ggtitle("A) Genetic Ancestry: projected PCA (unimputed)") +
    theme_light()


## import all unimputed PCA data
unimpPCAall <- read.csv("unimpPCA_allData.csv")
unimpPCAall$Region <- as.factor(unimpPCAall$Region)
## reorder factor levels for plotting
unimpPCAall$Region <- factor(unimpPCAall$Region, levels=c("North Central", "South Central", "balkan", "mediterranean", "HG", "anatoliaEF", "modern"))

ggplot(data=unimpPCAall, aes(x=-PC1, y=PC2, col=Region, stroke=0)) +
    geom_point() +
    scale_color_manual(values=palette4) +
    labs(x="PC1", y="PC2") +
    ggtitle("B) Genetic Ancestry: projected PCA (unimputed)") +
    theme_light()
```

